version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Python...."
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install pytest && pip3 install poetry
      - poetry install
  build:
    commands:
      - python3 test_file.py
