version: 0.2

env:
  variables:
    ENVIRONMENT: test
    # Set other neccessary environment variables here
    # These can also be set in AWS CodeBuild Console
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install pytest && pip3 install poetry
      - poetry install
  build:
    commands:
      - echo Running tests
      - pytest -s
cache:
  paths:
    - '/root/venv/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.cache/pypoetry/virtualenvs/**/*'
